include:
  - board: mriya_left
    artifact-name: mriya_left
  - board: mriya_right
    artifact-name: mriya_right
  - board: nice_nano/nrf52840/zmk
    shield: settings_reset
    artifact-name: prospector
